# Generated by Django 5.2.3 on 2025-06-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
