# Generated by Django 5.2.1 on 2025-05-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='orginal_price',
            new_name='original_price',
        ),
    ]
