# Generated by Django 5.2.4 on 2025-07-18 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_system', '0003_userprofile_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='registered_face_image',
        ),
    ]
