# Generated by Django 5.2.4 on 2025-07-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_system', '0004_remove_userprofile_registered_face_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registered_face_image',
            field=models.ImageField(blank=True, null=True, upload_to='medias/'),
        ),
    ]
