# Generated by Django 5.2.1 on 2025-05-31 04:58

import VIDFrame.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDFrame', '0003_alter_profile_contact_alter_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='media',
            name='media_type',
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=VIDFrame.models.upload_To_Medias),
        ),
        migrations.AddField(
            model_name='media',
            name='name',
            field=models.TextField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=100),
        ),
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
