# Generated by Django 5.2.1 on 2025-05-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDFrame', '0005_alter_media_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
