# Generated by Django 5.2.1 on 2025-05-31 15:12

import VIDFrame.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDFrame', '0006_media_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=VIDFrame.models.upload_To_Medias),
        ),
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=50),
        ),
    ]
