# Generated by Django 5.2.1 on 2025-06-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDFrame', '0007_alter_media_file_alter_media_name_alter_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='', max_length=50),
        ),
    ]
