# Generated by Django 5.2.1 on 2025-06-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDFrame', '0009_alter_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('', '--- Choose Media Type ---'), ('image', 'Image'), ('video', 'Video')], default='', max_length=50),
        ),
    ]
