# Generated by Django 5.2.1 on 2025-06-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDFrame', '0010_alter_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacomment',
            name='comment_text',
            field=models.TextField(max_length=250),
        ),
    ]
